<?php


return [
	'id' => 1,
	'hex' => 'Ok5kxWz9yiW',
	'meta_title' => 'True Crime Metrix - More True Crime that anywhere else on the planet',
	'meta_description' => 'Library of true crime cases. True crime news and information about the criminals, victims, judges, lawyers and true crime cases.',
	'meta_keywords' => 'true crime, crime news, true crime news, trial news',
	'meta_author' => 'True Crime Metrix',
	'meta_image' => NULL,
	'contact_email' => 'hello@truecrimemetrix.com',
	'copyright' => 'True Crime Metrix, Inc.',
	'powered_by' => 'Soapboxcoder',
	'powered_by_link' => 'https://soapboxcoder.com',
	'allow_registration' => 0,
	'allow_comments' => 0,
	'facebook_url' => NULL,
	'twitter_url' => NULL,
	'youtube_url' => NULL,
	'instagram_url' => NULL,
	'content_image_width' => 1200,
	'content_image_height' => 675,
	'pagination_items' => 12,
	'environment' => 'development',
	'css_assets' => 'app-de499434.css',
	'js_assets' => 'app-c8a58f85.js',
	'google_analytics_tag' => 'G-41956QHQLE',
	'created_at' => '2023-12-27 18:39:25',
	'updated_at' => '2023-12-27 18:39:25',
	'site_offline' => 0,
];